name: places
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  image_picker: ^0.8.5+3
  path_provider: ^2.0.15
  path: ^1.8.2
  sqflite: ^2.3.3+1
  cupertino_icons: ^1.0.6
  location: ^6.0.2
  google_maps_flutter: ^2.2.5
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
